### ISSUE TITLE
Case with 0.1+0.2

### ISSUE THREAD

**Issue by or4** [LesterLyu/fast-formula-parser#29]
Please help, how I should work with cases like 0.1+0.2, I got invalid value, I fixed it by toFixed(15), but I have problem with case 0.2^-2, where result is 24.999999999996
Should I create fork and implement math ops with big.js?

**Comment by LesterLyu** [comment]
`24.999999999996` should be fine. See [link](https://www.microsoft.com/en-us/microsoft-365/blog/2008/04/10/understanding-floating-point-precision-aka-why-does-excel-give-me-seemingly-wrong-answers/#:~:text=The%20precision%20of%20a%20number,within%2015%20digits%20of%20precision.)
If you want to display the number, please use [SSF](https://github.com/LesterLyu/fast-formula-parser/blob/master/ssf/ssf.js) to format the value into number format.

**Comment by LesterLyu** [comment]
Also keep in mind `big.js` is super slow in calculation, which is not ideal.
See [the benchmark](https://github.com/MikeMcl/big.js/issues/44#issuecomment-425940317).

**Comment by xfournet** [comment]
Just have to deal with that problematic, and I agree with @LesterLyu there is no need for `big.js` for such use case. You would need it only if you need number with more than 15 significant digits.

@or4 you should instead `toPrecision(15)` instead of `toFixed(15)` so you can cut the number precision whatever the number of digit before or after the dot. See https://stackoverflow.com/a/36369703

Both JS and Excel use [IEEE-754 double precision](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) which can have 15 to 17 significant digits. While Excel retain 15 digits when representing number, JS can retain up to 17 digits with the risk of having inaccurate 16th & 17th digits. While it's better for computation, it's not desirable for representation where you should limit to 15 digits to have only accurate digits

Demo in JS, you can compare that `toPrecision(15)` works as in Excel (when formatting with enough decimal)
```
n = 0.2**-2;
console.log(n);
console.log(Number(n.toFixed(15)));
console.log(Number(n.toPrecision(15)));
console.log();

n = 0.1+0.2;
console.log(n);
console.log(Number(n.toFixed(15)));
console.log(Number(n.toPrecision(15)));
console.log();

n = 1234567890123451234;
console.log(n);
console.log(Number(n.toFixed(15)));
console.log(Number(n.toPrecision(15)));
console.log();
```

```
24.999999999999996
24.999999999999996
25

0.30000000000000004
0.3
0.3

1234567890123451100
1234567890123451100
1234567890123450000
```

@LesterLyu should the documentation updated with that information that can help people to deal with that ? And the demo too ?

**Comment by or4** [comment]
hi, gus, thanks a lot for answers
it is very useful, thanks again!
